from __future__ import annotations

import hashlib
import os
from dataclasses import dataclass
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Any

from apps.api.app.services.role_inference_service import RoleInferenceService
from src.models.cv.extract_cv_info import extract_cv_info


def _safe_intent(intent: str, query: str) -> str:
    raw = (intent or "").strip().lower()
    if raw in {"score", "recommend", "improve_cv"}:
        return raw
    q = (query or "").strip().lower()
    if any(k in q for k in ["goi y", "recommend", "job", "cong viec"]):
        return "recommend"
    if any(k in q for k in ["cai thien", "improve", "roadmap", "gap"]):
        return "improve_cv"
    return "score"


def _make_internal_cv_id(*, cv_record: dict[str, Any], source_text: str, source_path: str) -> str:
    seed = "|".join(
        [
            str(cv_record.get("cv_id") or ""),
            str(cv_record.get("email") or ""),
            str(cv_record.get("phone") or ""),
            source_path,
            source_text[:5000],
        ]
    )
    return hashlib.sha256(seed.encode("utf-8")).hexdigest()[:16]


@dataclass
class CareerAnalysisService:
    role_profiles_path: str | Path

    def _extract_from_text(self, *, cv_text: str, cv_filename: str | None) -> dict[str, Any]:
        suffix = ".txt"
        if cv_filename:
            ext = Path(cv_filename).suffix.lower()
            if ext in {".txt", ".pdf", ".docx"}:
                suffix = ext

        with NamedTemporaryFile(mode="w", encoding="utf-8", suffix=suffix, delete=False) as tmp:
            tmp.write(cv_text)
            tmp_path = tmp.name
        try:
            return extract_cv_info(tmp_path)
        finally:
            try:
                os.remove(tmp_path)
            except OSError:
                pass

    def _extract_cv_record(
        self,
        *,
        cv_text: str | None,
        cv_file_path: str | None,
        cv_filename: str | None,
    ) -> tuple[dict[str, Any], str, str]:
        if cv_file_path:
            p = Path(cv_file_path)
            if not p.exists() or not p.is_file():
                raise FileNotFoundError(f"cv_file_path not found: {cv_file_path}")
            rec = extract_cv_info(str(p))
            return rec, "file_path", str(p.resolve())

        text = (cv_text or "").strip()
        if not text:
            raise ValueError("Either cv_text or cv_file_path is required.")
        rec = self._extract_from_text(cv_text=text, cv_filename=cv_filename)
        return rec, "raw_text", "in_memory_text"

    def analyze(
        self,
        *,
        intent: str,
        query: str,
        preferred_role: str | None,
        cv_text: str | None,
        cv_file_path: str | None,
        cv_filename: str | None,
        debug: bool = False,
    ) -> dict[str, Any]:
        cv_record, source_type, source_ref = self._extract_cv_record(
            cv_text=cv_text,
            cv_file_path=cv_file_path,
            cv_filename=cv_filename,
        )
        internal_cv_id = _make_internal_cv_id(
            cv_record=cv_record,
            source_text=str(cv_text or ""),
            source_path=str(source_ref),
        )

        role_result = RoleInferenceService(self.role_profiles_path).infer(
            cv_record=cv_record,
            preferred_role=preferred_role,
            query=query,
            top_k=3,
        )
        normalized_intent = _safe_intent(intent, query)

        next_actions = [
            "parse_cv_completed",
            f"run_{normalized_intent}_pipeline",
        ]
        if role_result.get("requires_confirmation"):
            next_actions.insert(1, "confirm_target_role_with_user")

        notes = [
            "internal_cv_id is generated by backend and hidden from end-users.",
            "role inference uses extracted CV signals + role profiles.",
        ]

        out = {
            "cv_snapshot": {
                "internal_cv_id": internal_cv_id,
                "source_type": source_type,
                "extracted_target_role": str(cv_record.get("target_role") or "Unknown"),
                "experience_years": str(cv_record.get("experience_years") or "Unknown"),
                "skills": [str(x) for x in (cv_record.get("skills") or [])][:20],
                "projects_count": len(cv_record.get("projects") or []),
            },
            "role_inference": role_result,
            "orchestration": {
                "intent": normalized_intent,
                "next_actions": next_actions,
                "notes": notes,
            },
        }
        if debug:
            out["debug_payload"] = {
                "query": query,
                "preferred_role": preferred_role,
                "cv_extract_preview": {
                    "email": cv_record.get("email", ""),
                    "target_role": cv_record.get("target_role", ""),
                    "skills_count": len(cv_record.get("skills") or []),
                },
            }
        return out
